public class myController1 {

    public String getRend() {
        return null;
    }


    public PageReference commandLinkAction() {
        return null;
    }


private final Account account;

    public MyController1() {
       Account account = new Account();
    }

    public Account getAccount() {
    insert account;
        return account;

    }
     public PageReference save() {
        update account;
        return null;

    }


}